# Generated by Django 6.0.3 on 2026-03-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
        ("estate", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estate",
            name="images",
            field=models.ManyToManyField(
                blank=True, to="common.media", verbose_name="Images"
            ),
        ),
    ]
