# Generated by Django 6.0.3 on 2026-03-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estate", "0002_alter_estate_images"),
    ]

    operations = [
        migrations.RenameField(
            model_name="estate",
            old_name="curreny",
            new_name="currency",
        ),
        migrations.AddField(
            model_name="estate",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
    ]
