# Generated by Django 6.0.3 on 2026-03-18 08:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estate", "0003_rename_curreny_estate_currency_estate_is_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="estateagent",
            old_name="fasebook",
            new_name="facebook",
        ),
        migrations.AddField(
            model_name="estate",
            name="is_featured",
            field=models.BooleanField(default=False, verbose_name="Is featured"),
        ),
        migrations.AddField(
            model_name="estateagent",
            name="rating",
            field=models.DecimalField(
                decimal_places=1,
                default=5,
                max_digits=2,
                validators=[
                    django.core.validators.MaxValueValidator(5),
                    django.core.validators.MinValueValidator(0),
                ],
                verbose_name="Rating",
            ),
        ),
        migrations.AlterField(
            model_name="estate",
            name="latitude",
            field=models.DecimalField(
                decimal_places=9, max_digits=12, verbose_name="Latitude"
            ),
        ),
        migrations.AlterField(
            model_name="estate",
            name="longitude",
            field=models.DecimalField(
                decimal_places=9, max_digits=12, verbose_name="Longitude"
            ),
        ),
    ]
