# Generated by Django 6.0.3 on 2026-03-19 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('estate', '0004_rename_fasebook_estateagent_facebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estateagent',
            name='avatar',
        ),
        migrations.AddField(
            model_name='estateagent',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='common.media', verbose_name='Images'),
        ),
    ]
