# Generated by Django 6.0.3 on 2026-03-23 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estate", "0005_remove_estateagent_avatar_estateagent_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="estateagentcomment",
            name="stars_count",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(5),
                    django.core.validators.MinValueValidator(0),
                ],
                verbose_name="Stars Count",
            ),
        ),
    ]
