# Generated by Django 6.0.3 on 2026-03-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estate", "0006_estateagentcomment_stars_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="estate",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, null=True, verbose_name="Slug"
            ),
        ),
    ]
