# Generated by Django 6.0.3 on 2026-03-25 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
        ("estate", "0007_estate_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="estateagent",
            name="images",
        ),
        migrations.AddField(
            model_name="estateagent",
            name="avatar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="common.media",
                verbose_name="Avatar",
            ),
        ),
    ]
